version: "3.2"

services:
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
        volumes:
            - redis:/var/lib/redis
        networks:
            - printmeat

    app:
        build:
            context: ./
        ports:
            - 80:8080
        networks:
            - printmeat
        depends_on:
            - redis

volumes:
    redis:
        driver: local

networks:
    printmeat: